### ISSUE TITLE
Create two vagrant machines that can communicate with each other

### ISSUE THREAD

**Issue by sverch** [sverch/butter-cloud#1]
## Description

Having VMs in which we can run all the tests for this project will be important, so that we can have a deterministic starting point every time we run the tests, and can be sure that different people are running the same thing.

I would suggest [Vagrant](https://www.vagrantup.com/) for this. They try to make this easy to set up. The networking documentation lives here: https://developer.hashicorp.com/vagrant/docs/networking

## Done When

- A `Vagrantfile` exists and is committed to the repo that can create the VMs.
- There's some kind of test script that can be run to verify the setup works.
- This is all documented.
- There's documentation for why the specific configuration for networking was chosen over the others (maybe as a comment in the `Vagrantfile`).

**Comment by christopherverch** [comment]
cool story tell it again

**Comment by sverch** [comment]
Ok, but just one more time... Then you have to go to bed.

## Description

Having VMs in which we can run all the tests for this project will be important, so that we can have a deterministic starting point every time we run the tests, and can be sure that different people are running the same thing.

I would suggest [Vagrant](https://www.vagrantup.com/) for this. They try to make this easy to set up. The networking documentation lives here: https://developer.hashicorp.com/vagrant/docs/networking

## Done When

- A `Vagrantfile` exists and is committed to the repo that can create the VMs.
- There's some kind of test script that can be run to verify the setup works.
- This is all documented.
- There's documentation for why the specific configuration for networking was chosen over the others (maybe as a comment in the `Vagrantfile`.

**Comment by sverch** [comment]
This is done!
